apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-config
  namespace: dev
data:
  EUREKA_SERVER_PORT: "8761"
  EUREKA_INSTANCE_HOSTNAME: "eureka-service"
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
  EUREKA_CLIENT_FETCH_REGISTRY: "false"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-service:8761/eureka"

