apiVersion: v1
kind: Service
metadata:
  name: eureka-service-nodeport
  namespace: dev
spec:
  selector:
    app: eureka-service
  type: NodePort
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 32061 
