version: '3.8'
name: e-commerce-store

services:
  # -----------------------------
  # PostgreSQL Databases
  # -----------------------------
  db-users:
    container_name: db-users
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    volumes:
      - db-pgdata-users:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - e-commerce-store

  db-inventory:
    container_name: db-inventory
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory
    volumes:
      - db-pgdata-inventory:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - e-commerce-store

  db-reviews:
    container_name: db-reviews
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reviews
    volumes:
      - db-pgdata-reviews:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - e-commerce-store

  db-orders:
    container_name: db-orders
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orders
    volumes:
      - db-pgdata-orders:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - e-commerce-store

  # -----------------------------
  # Eureka Service Registry
  # -----------------------------
  eureka-service:
    container_name: eureka-service
    image: eureka-service:latest
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: unless-stopped
    networks:
      - e-commerce-store

  # -----------------------------
  # API Gateway
  # -----------------------------
  api-gateway:
    container_name: api-gateway
    image: api-gateway:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-service
    restart: unless-stopped
    networks:
      - e-commerce-store

  # -----------------------------
  # Microservices
  # -----------------------------
  user-service:
    container_name: user-service
    image: user-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db-users
      - eureka-service
    restart: unless-stopped
    networks:
      - e-commerce-store

  auth-service:
    container_name: auth-service
    image: auth-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - user-service
      - eureka-service
    restart: unless-stopped
    networks:
      - e-commerce-store

  inventory-service:
    container_name: inventory-service
    image: inventory-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db-inventory
      - eureka-service
    restart: unless-stopped
    networks:
      - e-commerce-store

  order-service:
    container_name: order-service
    image: order-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db-orders
      - broker
      - eureka-service
    restart: unless-stopped
    networks:
      - e-commerce-store

  reviews-service:
    container_name: reviews-service
    image: reviews-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db-reviews
      - eureka-service
    restart: unless-stopped
    networks:
      - e-commerce-store

  notification-service:
    container_name: notification-service
    image: notification-service:latest
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-service
    restart: unless-stopped
    networks:
      - e-commerce-store

  # -----------------------------
  # Zookeeper (Required for Kafka)
  # -----------------------------
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    restart: unless-stopped
    networks:
      - e-commerce-store

  # -----------------------------
  # Kafka Broker
  # -----------------------------
  broker:
    container_name: broker
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    expose:
      - "29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: unless-stopped
    networks:
      - e-commerce-store

  # -----------------------------
  # Kafka Init (Create Topics)
  # -----------------------------
  init-broker:
    container_name: init-broker
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - broker
    entrypoint: ['/bin/sh', '-c']
    command: |
      "
      echo 'Waiting for Kafka...'
      sleep 10
      kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic order.created.v1
      kafka-topics --bootstrap-server broker:29092 --list
      "
    networks:
      - e-commerce-store

  # -----------------------------
  # Observability Stack
  # -----------------------------
  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector-contrib:0.96.0
    restart: unless-stopped
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yaml
    volumes:
      - ./otel-collector/otel-collector.yaml:/etc/otelcol-contrib/otel-collector.yaml
    networks:
      - e-commerce-store

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - e-commerce-store

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - e-commerce-store

  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - e-commerce-store

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - e-commerce-store

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
    networks:
      - e-commerce-store

# -----------------------------
# Volumes
# -----------------------------
volumes:
  db-pgdata-users:
  db-pgdata-inventory:
  db-pgdata-reviews:
  db-pgdata-orders:

# -----------------------------
# Network
# -----------------------------
networks:
  e-commerce-store:
    driver: bridge
