apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ecommerce
data:
  POSTGRES_DB: "{{ .Values.postgres.db }}"
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
