apiVersion: v1
kind: Service
metadata:
  name: reviews-service
  namespace: ecommerce
spec:
  selector:
    app: reviews-service
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
