apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: dev

  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ecommerce
  SPRING_DATASOURCE_USERNAME: ecommerce
  SPRING_DATASOURCE_PASSWORD: ecommerce

  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
  EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
  EUREKA_CLIENT_FETCH_REGISTRY: "true"

